[package]
name = "rust_thread_pool"
version = "0.1.0"
authors = ["Wei Liu <sunnywhy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13"
